services:
  vue-app:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:5173"
    env_file:
      - .env
    volumes:
      - ./vite-project:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: menu_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:password@db:${DB_PORT}/menu_db
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    command: bash -c "until pg_isready -h db -p ${DB_PORT}; do sleep 1; done; npm run dev"


volumes:
  postgres_data: